title: clangd
description: turn your editor into a C++ IDE
plugins:
- jekyll-optional-front-matter
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-redirect-from
markdown: kramdown
kramdown:
  parse_block_html: true
